version: '3.8'
services:
  app:
    image: borisnieuwen/secret_model:0.1
    container_name: secret-model-runner
    ports:
      - "5001:50051"
      - "5002:50052"
      - "80:8001"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
    environment:
      - SSL_CERT=${SSL_CERT}
      - SSL_KEY=${SSL_KEY}
